GET http://127.0.0.1:9527/user/find-by-page
tenant-name: myfavs_master

#################
GET http://127.0.0.1:9527/user/find-by-page
tenant-name: myfavs_tenant1

#################
GET http://127.0.0.1:9527/user/find-by-page
tenant-name: myfavs_tenant2