package work.myfavs.framework.orm;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import work.myfavs.framework.orm.meta.DbType;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Savepoint;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class DatabaseUnitTest {

  @Mock
  private DBTemplate dbTemplate;

  @Mock
  private ConnFactory connFactory;

  private DBConfig   dbConfig;
  private Database   database;
  private Connection connection;

  @Before
  public void setUp() throws SQLException {
    MockitoAnnotations.openMocks(this);

    dbConfig = new DBConfig();
    dbConfig.setDbType(DbType.H2);

    connection = mock(Connection.class);
    when(connection.getAutoCommit()).thenReturn(false);
    when(connection.isClosed()).thenReturn(false);

    when(dbTemplate.getConnectionFactory()).thenReturn(connFactory);
    when(dbTemplate.getDbConfig()).thenReturn(dbConfig);
    when(connFactory.openConnection()).thenReturn(connection);
    when(connFactory.getCurrentConnection()).thenReturn(connection);

    database = new Database(dbTemplate);
  }

  // region open / close

  @Test
  public void open_ShouldReturnThisAndOpenConnection() {
    Database result = database.open();
    assertSame(database, result);
    verify(connFactory, times(2)).openConnection();
  }

  @Test
  public void close_ShouldCloseQueryAndReleaseConnection() {
    database.close();
    verify(connFactory).closeConnection(connection);
  }

  @Test
  public void close_ShouldCloseQueryAndResetState() {
    database.createQuery("SELECT 1");
    database.close();
    // After close, the connection should have been released
    verify(connFactory).closeConnection(connection);
  }

  // endregion

  // region isSqlServer / isMySql

  @Test
  public void isSqlServer_ShouldReturnTrue_WhenDbTypeIsSqlServer() {
    dbConfig.setDbType(DbType.SQL_SERVER);
    assertTrue(database.isSqlServer());
  }

  @Test
  public void isSqlServer_ShouldReturnTrue_WhenDbTypeIsSqlServer2012() {
    dbConfig.setDbType(DbType.SQL_SERVER_2012);
    assertTrue(database.isSqlServer());
  }

  @Test
  public void isSqlServer_ShouldReturnFalse_WhenDbTypeIsMySql() {
    dbConfig.setDbType(DbType.MYSQL);
    assertFalse(database.isSqlServer());
  }

  @Test
  public void isSqlServer_ShouldReturnFalse_WhenDbTypeIsH2() {
    dbConfig.setDbType(DbType.H2);
    assertFalse(database.isSqlServer());
  }

  @Test
  public void isMySql_ShouldReturnTrue_WhenDbTypeIsMySql() {
    dbConfig.setDbType(DbType.MYSQL);
    assertTrue(database.isMySql());
  }

  @Test
  public void isMySql_ShouldReturnFalse_WhenDbTypeIsNotMySql() {
    dbConfig.setDbType(DbType.POSTGRE_SQL);
    assertFalse(database.isMySql());
  }

  // endregion

  // region getXxx

  @Test
  public void getDbConfig_ShouldReturnConfig() {
    assertSame(dbConfig, database.getDbConfig());
  }

  @Test
  public void getDbTemplate_ShouldReturnTemplate() {
    assertSame(dbTemplate, database.getDbTemplate());
  }

  @Test
  public void getConnection_ShouldReturnCurrentConnection() {
    assertSame(connection, database.getConnection());
    verify(connFactory).getCurrentConnection();
  }

  // endregion

  // region createQuery

  @Test
  public void createQuery_ShouldDelegateToCreateQueryWithAutoGeneratedPKFalse() {
    Query query = database.createQuery("SELECT 1");
    assertNotNull(query);
    // Creating again should reuse (due to caching/reuse pattern)
    Query query2 = database.createQuery("SELECT 2");
    assertSame(query, query2);
  }

  @Test
  public void createQuery_WithAutoGeneratedPK_ShouldCreateQueryWithFlag() {
    Query query = database.createQuery("INSERT INTO t VALUES (?)", true);
    assertNotNull(query);
  }

  // endregion

  // region createOrm

  @Test
  public void createOrm_ShouldReturnSameInstance_OnRepeatedCalls() {
    work.myfavs.framework.orm.orm.Orm orm1 = database.createOrm();
    work.myfavs.framework.orm.orm.Orm orm2 = database.createOrm();
    assertNotNull(orm1);
    assertSame(orm1, orm2);
  }

  @Test
  public void createOrm_ShouldReturnDifferentInstance_AfterClose() {
    work.myfavs.framework.orm.orm.Orm orm1 = database.createOrm();
    database.close();
    work.myfavs.framework.orm.orm.Orm orm2 = database.createOrm();
    assertNotNull(orm1);
    assertNotNull(orm2);
    assertNotSame(orm1, orm2);
  }

  // endregion

  // region setSavepoint

  @Test
  public void setSavepoint_ShouldReturnSavepoint_WhenConnectionExists() throws SQLException {
    Savepoint expected = mock(Savepoint.class);
    when(connection.setSavepoint()).thenReturn(expected);

    Savepoint actual = database.setSavepoint();
    assertSame(expected, actual);
    verify(connection).setSavepoint();
  }

  @Test
  public void setSavepoint_WithName_ShouldReturnNamedSavepoint() throws SQLException {
    Savepoint expected = mock(Savepoint.class);
    when(connection.setSavepoint("sp1")).thenReturn(expected);

    Savepoint actual = database.setSavepoint("sp1");
    assertSame(expected, actual);
    verify(connection).setSavepoint("sp1");
  }

  @Test(expected = work.myfavs.framework.orm.util.exception.ConnectionException.class)
  public void setSavepoint_ShouldThrow_WhenConnectionIsNull() {
    when(connFactory.getCurrentConnection()).thenReturn(null);
    database.setSavepoint();
  }

  // endregion

  // region rollback

  @Test
  public void rollback_ShouldDelegateToRollbackNull() throws SQLException {
    database.rollback();
    verify(connection).rollback();
  }

  @Test
  public void rollback_WithSavepoint_ShouldRollbackToSavepoint() throws SQLException {
    Savepoint sp = mock(Savepoint.class);
    database.rollback(sp);
    verify(connection).rollback(sp);
  }

  @Test
  public void rollback_ShouldDoNothing_WhenConnectionIsNull() throws SQLException {
    when(connFactory.getCurrentConnection()).thenReturn(null);
    database.rollback(); // should not throw
    verify(connection, never()).rollback();
  }

  // endregion

  // region commit

  @Test
  public void commit_ShouldCallCommit_WhenAutoCommitIsFalseAndNotClosed() throws SQLException {
    database.commit();
    verify(connection).commit();
  }

  @Test
  public void commit_ShouldSkip_WhenConnectionIsNull() throws SQLException {
    when(connFactory.getCurrentConnection()).thenReturn(null);
    database.commit();
    verify(connection, never()).commit();
  }

  @Test
  public void commit_ShouldSkip_WhenAutoCommitIsTrue() throws SQLException {
    when(connection.getAutoCommit()).thenReturn(true);
    database.commit();
    verify(connection, never()).commit();
  }

  @Test
  public void commit_ShouldSkip_WhenConnectionIsClosed() throws SQLException {
    when(connection.isClosed()).thenReturn(true);
    database.commit();
    verify(connection, never()).commit();
  }

  @Test(expected = work.myfavs.framework.orm.util.exception.ConnectionException.class)
  public void commit_ShouldThrow_OnSQLException() throws SQLException {
    doThrow(new SQLException("commit failed")).when(connection).commit();
    database.commit();
  }

  // endregion
}
