package work.myfavs.framework.orm;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import work.myfavs.framework.orm.meta.DbType;
import work.myfavs.framework.orm.util.exception.DataRetrievalException;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

public class QueryUnitTest {

  @Mock
  private DBTemplate dbTemplate;

  @Mock
  private ConnFactory connFactory;

  private DBConfig   dbConfig;
  private Database   database;
  private Connection connection;
  private PreparedStatement preparedStatement;

  @Before
  public void setUp() throws SQLException {
    MockitoAnnotations.openMocks(this);

    dbConfig = new DBConfig();
    dbConfig.setDbType(DbType.H2);

    connection = mock(Connection.class);
    preparedStatement = mock(PreparedStatement.class);

    when(connection.getAutoCommit()).thenReturn(false);
    when(connection.isClosed()).thenReturn(false);
    when(connection.prepareStatement(anyString())).thenReturn(preparedStatement);
    when(connection.prepareStatement(anyString(), anyInt())).thenReturn(preparedStatement);

    when(dbTemplate.getConnectionFactory()).thenReturn(connFactory);
    when(dbTemplate.getDbConfig()).thenReturn(dbConfig);
    when(connFactory.openConnection()).thenReturn(connection);
    when(connFactory.getCurrentConnection()).thenReturn(connection);

    database = new Database(dbTemplate);
  }

  // region createQuery lifecycle

  @Test
  public void createQuery_ShouldResetState() {
    Query query = database.createQuery("SELECT 1");
    assertNotNull(query);

    Query same = query.createQuery("SELECT 2");
    assertSame(query, same);
  }

  @Test
  public void createQuery_WithoutArg_ShouldDefaultAutoGeneratedPKToFalse() {
    Query query = database.createQuery("SELECT 1");
    assertNotNull(query);
    // calling execute should not try to get generated keys
  }

  @Test
  public void createQuery_ShouldClearOldPreparedStatement() throws SQLException {
    Query query = database.createQuery("SELECT 1");
    // trigger creation of preparedStatement via execute
    when(preparedStatement.executeUpdate()).thenReturn(1);
    query.execute();

    // now create a new query with different SQL
    query.createQuery("SELECT 2");

    // The old preparedStatement should be closed and set to null
    verify(preparedStatement).close();
  }

  // endregion

  // region close / closed flag

  @Test
  public void close_ShouldMakeOperationsThrow() {
    Query query = database.createQuery("SELECT 1");

    query.close();

    // After close, operations should throw
    try {
      query.execute();
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains("已关闭"));
    }
  }

  @Test
  public void close_ShouldClosePreparedStatement() throws SQLException {
    Query query = database.createQuery("SELECT 1");
    when(preparedStatement.executeUpdate()).thenReturn(1);
    query.execute();

    query.close();
    verify(preparedStatement, times(1)).close(); // closed once by Query.close()
  }

  @Test
  public void operations_ShouldThrow_WhenQueryIsClosed() {
    Query query = database.createQuery("SELECT 1");
    query.close();

    try {
      query.addParameter(1, "test");
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains("已关闭"));
    }

    try {
      query.addParameters(List.of("a"));
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains("已关闭"));
    }

    try {
      query.addBatch();
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains("已关闭"));
    }

    try {
      query.executeBatch();
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains("已关闭"));
    }

    try {
      query.find(String.class);
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains("已关闭"));
    }

    try {
      query.get(String.class);
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains("已关闭"));
    }
  }

  // endregion

  // region addParameter / addParameters

  @Test
  public void addParameter_WithIndexLessThanOne_ShouldThrow() {
    Query query = database.createQuery("SELECT ? FROM dual");
    try {
      query.addParameter(0, "test");
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains(">= 1"));
    }
  }

  @Test
  public void addParameter_WithNegativeIndex_ShouldThrow() {
    Query query = database.createQuery("SELECT ? FROM dual");
    try {
      query.addParameter(-1, "test");
      fail("Expected DataRetrievalException");
    } catch (DataRetrievalException e) {
      assertTrue(e.getMessage().contains(">= 1"));
    }
  }

  @Test
  public void addParameter_WithValidIndex_ShouldSucceed() {
    Query query = database.createQuery("SELECT ? FROM dual");
    query.addParameter(1, "hello");
    // No exception expected
  }

  @Test
  public void addParameter_WithoutIndex_ShouldSucceed() {
    Query query = database.createQuery("SELECT ? FROM dual");
    query.addParameter("hello");
    // No exception expected
  }

  @Test
  public void addParameters_WithEmptyCollection_ShouldReturnEarly() {
    Query query = database.createQuery("SELECT ? FROM dual");
    query.addParameters(Collections.emptyList());
    // No exception expected
  }

  @Test
  public void addParameters_WithNullCollection_ShouldReturnEarly() {
    Query query = database.createQuery("SELECT ? FROM dual");
    query.addParameters((List<?>) null);
    // No exception expected
  }

  @Test
  public void addParameters_WithValues_ShouldSucceed() {
    Query query = database.createQuery("SELECT ?, ? FROM dual");
    query.addParameters(List.of("a", "b"));
    // No exception expected
  }

  // endregion

  // region execute

  @Test
  public void execute_ShouldCallExecuteUpdate() throws SQLException {
    Query query = database.createQuery("UPDATE t SET name = ?");
    when(preparedStatement.executeUpdate()).thenReturn(2);

    int result = query.execute();
    assertEquals(2, result);
    verify(preparedStatement).executeUpdate();
  }

  @Test
  public void execute_WithConfigConsumer_ShouldApplyConfiguration() throws SQLException {
    Query query = database.createQuery("UPDATE t SET name = ?");
    when(preparedStatement.executeUpdate()).thenReturn(1);

    int result = query.execute(
        ps -> ps.setQueryTimeout(10),
        null
    );

    assertEquals(1, result);
    verify(preparedStatement).setQueryTimeout(10);
    verify(preparedStatement).executeUpdate();
  }

  @Test
  public void execute_WithKeysConsumer_ShouldProcessGeneratedKeys() throws SQLException {
    Query query = database.createQuery("INSERT INTO t VALUES (?)", true);
    ResultSet generatedKeys = mock(ResultSet.class);
    when(preparedStatement.getGeneratedKeys()).thenReturn(generatedKeys);
    when(preparedStatement.executeUpdate()).thenReturn(1);

    final boolean[] consumed = {false};
    query.execute(null, rs -> {
      consumed[0] = true;
    });

    assertTrue(consumed[0]);
    verify(preparedStatement).getGeneratedKeys();
  }

  @Test(expected = DataRetrievalException.class)
  public void execute_ShouldThrowDataRetrievalException_OnSQLException() throws SQLException {
    Query query = database.createQuery("UPDATE t SET name = ?");
    when(preparedStatement.executeUpdate()).thenThrow(new SQLException("db error"));
    query.execute();
  }

  // endregion

  // region executeBatch / addBatch

  @Test
  public void addBatch_ShouldNotThrow() {
    Query query = database.createQuery("INSERT INTO t VALUES (?)");
    query.addBatch();
    // addBatch should not throw
  }

  @Test
  public void executeBatch_ShouldReturnEmptyArray_WhenNoBatchesAdded() throws SQLException {
    Query query = database.createQuery("INSERT INTO t VALUES (?)");

    when(preparedStatement.executeBatch()).thenReturn(new int[0]);
    // If no parameters, applyBatchParameters returns empty array
    // and executeBatch should return that
    int[] result = query.executeBatch();
    assertNotNull(result);
  }

  @Test
  public void executeBatch_WithParameters_ShouldExecute() throws SQLException {
    Query query = database.createQuery("INSERT INTO t VALUES (?)");

    query.addParameter(1, "a");
    query.addBatch();

    query.addParameter(1, "b");
    query.addBatch();

    when(preparedStatement.executeBatch()).thenReturn(new int[]{1, 1});
    int[] result = query.executeBatch();
    assertNotNull(result);
  }

  // endregion

  // endregion
}
