package work.myfavs.framework.orm.orm.component;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import work.myfavs.framework.orm.*;
import work.myfavs.framework.orm.entity.IdentityExample;
import work.myfavs.framework.orm.entity.SnowflakeExample;
import work.myfavs.framework.orm.meta.DbType;
import work.myfavs.framework.orm.orm.dialect.MySqlDialect;
import work.myfavs.framework.orm.meta.enumeration.GenerationType;
import work.myfavs.framework.orm.meta.schema.Attribute;
import work.myfavs.framework.orm.meta.schema.ClassMeta;
import work.myfavs.framework.orm.meta.schema.Metadata;
import work.myfavs.framework.orm.util.id.PKGenerator;

import java.util.List;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * {@link OrmInserter} 的单元测试。
 */
public class OrmInserterTest {

  @Mock
  private Database database;
  @Mock
  private DBTemplate dbTemplate;
  @Mock
  private Query query;
  @Mock
  private PKGenerator pkGenerator;

  private OrmSqlBuilder sqlBuilder;
  private OrmExecutor executor;
  private OrmInserter inserter;

  @Before
  public void setUp() {
    MockitoAnnotations.openMocks(this);
    DBConfig dbConfig = new DBConfig();
    dbConfig.setDbType(DbType.MYSQL);

    when(database.getDbTemplate()).thenReturn(dbTemplate);
    when(database.getDbConfig()).thenReturn(dbConfig);
    when(database.createQuery(anyString())).thenReturn(query);
    when(database.createQuery(anyString(), anyBoolean())).thenReturn(query);
    when(query.addParameters(any())).thenReturn(query);
    when(query.execute(any(), any())).thenReturn(1);
    when(dbTemplate.getPkGenerator()).thenReturn(pkGenerator);
    when(pkGenerator.nextSnowFakeId()).thenReturn(100L);
    when(pkGenerator.nextUUID()).thenReturn("mock-uuid-1234");

    sqlBuilder = new OrmSqlBuilder(MySqlDialect.INSTANCE);
    executor = new OrmExecutor(database);
    inserter = new OrmInserter(database, dbTemplate, sqlBuilder, executor);
  }

  @Test
  public void shouldReturnZeroWhenEntityIsNull() {
    int result = inserter.create(SnowflakeExample.class, (SnowflakeExample) null);
    assertEquals(0, result);
  }

  @Test
  public void shouldReturnZeroWhenCollectionIsEmpty() {
    int result = inserter.create(SnowflakeExample.class, List.of());
    assertEquals(0, result);
  }

  @Test
  public void shouldCreateSingleEntityWithSnowflakeId() {
    SnowflakeExample entity = new SnowflakeExample();
    entity.setName("Test");

    inserter.create(SnowflakeExample.class, entity);

    // Snowflake 策略应生成主键
    assertNotNull(entity.getId());
    verify(database).createQuery(anyString(), eq(false));
  }

  @Test
  public void shouldCreateEntityWithAssignedPk_WhenPkAlreadySet() {
    SnowflakeExample entity = new SnowflakeExample();
    entity.setId(999L);
    entity.setName("Assigned");

    inserter.create(SnowflakeExample.class, entity);

    assertEquals(Long.valueOf(999L), entity.getId());
    verify(database).createQuery(anyString(), eq(false));
  }

  @Test
  public void shouldCreateIdentityEntity() {
    IdentityExample entity = new IdentityExample();
    entity.setName("IdentityTest");

    inserter.create(IdentityExample.class, entity);

    // Identity 策略应设置 autoGeneratedPK=true
    verify(database).createQuery(anyString(), eq(true));
  }
}
