package work.myfavs.framework.orm;

import java.io.Closeable;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Savepoint;
import lombok.Getter;
import work.myfavs.framework.orm.meta.DbType;
import work.myfavs.framework.orm.orm.Orm;
import work.myfavs.framework.orm.orm.OrmFactory;
import work.myfavs.framework.orm.util.common.StringUtil;
import work.myfavs.framework.orm.util.exception.DBException;
import work.myfavs.framework.orm.util.func.ThrowingConsumer;
import work.myfavs.framework.orm.util.func.ThrowingFunction;

/**
 * 数据库
 */
public class Database implements Closeable {

  @Getter
  protected final DBTemplate  dbTemplate;
  protected final ConnFactory connFactory;

  private Query query;

  /**
   * 构造方法，建议通过 {@link DBTemplate#createDatabase()} 创建
   *
   * @param dbTemplate {@link DBTemplate}
   */
  public Database(DBTemplate dbTemplate) {
    this.dbTemplate  = dbTemplate;
    this.connFactory = dbTemplate.getConnectionFactory();
    this.open();
  }

  /**
   * 判断当前是否使用 SQL Server 数据库
   *
   * @return 如果是返回 {@code true}，否则返回 {@code false}
   */
  public boolean isSqlServer() {
    return StringUtil.equals(getDbConfig().getDbType(), DbType.SQL_SERVER)
        || StringUtil.equals(getDbConfig().getDbType(), DbType.SQL_SERVER_2012);
  }

  /**
   * 判断当前是否使用 MySql 数据库
   *
   * @return 如果是返回 {@code true}，否则返回 {@code false}
   */
  public boolean isMySql() {
    return StringUtil.equals(getDbConfig().getDbType(), DbType.MYSQL);
  }

  /**
   * 获取ORM数据库配置
   *
   * @return {@link DBTemplate#getDbConfig()}
   */
  public DBConfig getDbConfig() {
    return this.dbTemplate.getDbConfig();
  }


  public Connection getConnection() {
    return this.connFactory.getCurrentConnection();
  }

  /**
   * 打开数据库连接，需要与 {@link #close()} 配对使用
   *
   * @return 如果连接不存在，则创建，否则记录数据库连接打开次数 {@code +1}，并返回 {@link ConnFactory#openConnection()}
   */
  @SuppressWarnings("resource")
  public Database open() {
    this.connFactory.openConnection();
    return this;
  }


  /**
   * 释放数据库资源，与 {@link #open()} 配对使用 <br/>
   * 如果数据库连接打开次数 {@code > 1} ，则记录数据库连接次数 {@code -1} <br/>
   * 如果数据库连接打开次数 {@code = 1} ，则关闭数据库连接
   */
  @Override
  public void close() {
    if (null != this.query) {
      this.query.close();
    }
    this.connFactory.closeConnection(getConnection());
  }

  /**
   * 查询，设置 SQL 语句，并创建数据库 PrepareStatement 对象 <br>
   *
   * @param sql SQL 语句
   * @return {@link Database}
   */
  public Query createQuery(String sql) {
    return createQuery(sql, false);
  }

  /**
   * 查询，设置 SQL 语句，并创建数据库 PrepareStatement 对象 <br>
   *
   * @param sql             SQL 语句
   * @param autoGeneratedPK 是否生成主键
   * @return {@link Database}
   */
  public Query createQuery(String sql, boolean autoGeneratedPK) {
    if (null == this.query) {
      return this.query = new Query(this, sql, autoGeneratedPK);
    }
    return this.query.createQuery(sql, autoGeneratedPK);
  }

  public Orm createOrm() {
    return OrmFactory.createOrm(this);
  }


  public Savepoint setSavepoint() {
    try {
      return getConnection().setSavepoint();
    } catch (SQLException e) {
      throw new DBException(e, "设置 Savepoint 时发生异常: %s", e.getMessage());
    }
  }

  public Savepoint setSavepoint(String name) {
    try {
      return getConnection().setSavepoint(name);
    } catch (SQLException e) {
      throw new DBException(e, "设置 Savepoint 时发生异常: %s", e.getMessage());
    }
  }

  public void rollback() {
    rollback(null);
  }

  public void rollback(Savepoint savepoint) {
    try {
      if (null == savepoint) {
        getConnection().rollback();
        return;
      }
      getConnection().rollback(savepoint);

    } catch (SQLException e) {
      throw new DBException(e, "回滚事务时发生异常: %s", e.getMessage());
    }
  }

  public void commit() {

    Connection connection = getConnection();
    if (null == connection) {
      return;
    }

    try {
      if (connection.getAutoCommit()) {
        return;
      }
      if (connection.isClosed()) {
        return;
      }

      connection.commit();
    } catch (SQLException e) {
      throw new DBException(e, "提交事务时发生异常: %s", e.getMessage());
    }
  }

  /**
   * 在事务中执行 {@link ThrowingFunction#apply(Object)}
   *
   * @param func      {@link ThrowingFunction} function
   * @param <TResult> function 返回结果类型
   * @return {@link ThrowingFunction#apply(Object) func.apply(Object)}
   */
  public <TResult> TResult tx(ThrowingFunction<Orm, TResult, SQLException> func) {

    return tx(func, () -> {});
  }

  /**
   * 在事务中执行 {@link ThrowingFunction#apply(Object)}，并在事务完成后执行 {@link Runnable#run()}
   *
   * @param func      {@link ThrowingFunction} function
   * @param callback  {@link Runnable} callback
   * @param <TResult> function 返回结果类型
   * @return {@link ThrowingFunction#apply(Object) func.apply(Object)}
   */
  public <TResult> TResult tx(ThrowingFunction<Orm, TResult, SQLException> func, Runnable callback) {

    try (Database database = this.open()) {
      Orm     orm    = database.createOrm();
      TResult result = func.apply(orm);
      database.commit();
      return result;
    } catch (SQLException e) {
      this.rollback();
      throw new DBException(e, "执行事务过程中发生异常: %s", e.getMessage());
    } finally {
      callback.run();
    }
  }

  /**
   * 在事务中执行 {@link ThrowingConsumer#accept(Object)}
   *
   * @param consumer {@link ThrowingConsumer} consumer
   */
  public void tx(ThrowingConsumer<Orm, SQLException> consumer) {

    tx(consumer, () -> {});
  }

  /**
   * 在事务中执行 {@link ThrowingConsumer#accept(Object)}，并在事务完成后执行 {@link Runnable#run()}
   *
   * @param consumer {@link ThrowingConsumer} consumer
   * @param callback {@link Runnable} callback
   */
  public void tx(ThrowingConsumer<Orm, SQLException> consumer, Runnable callback) {

    try (Database database = this.open()) {
      Orm orm = database.createOrm();
      consumer.accept(orm);
      database.commit();
    } catch (SQLException e) {
      this.rollback();
      throw new DBException(e, "执行事务过程中发生异常: %s", e.getMessage());
    } finally {
      callback.run();
    }
  }
}
