package work.myfavs.framework.orm;

import work.myfavs.framework.orm.meta.dialect.IDialect;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.util.Collection;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

public interface IDatabase {

  /**
   * 获取ORM配置
   *
   * @return ORM配置
   */
  DBConfig dbConfig();

  /**
   * 获取数据库方言
   *
   * @return 数据库方言
   */
  IDialect dialect();

  /**
   * 获取数据库连接工厂
   *
   * @return 数据库连接工厂
   */
  ConnFactory connFactory();

  /**
   * 执行事务(带返回值)
   *
   * @param supplier Supplier
   * @return R
   * @param <R> 返回值类型
   */
  <R> R tx(Supplier<R> supplier);

  /**
   * 执行事务(无返回值)
   *
   * @param runnable Supplier
   */
  void tx(Runnable runnable);

  /**
   * 调用存储过程
   *
   * @param sql 调用存储过程语句，如：{ call proc_name(?,?,?)}
   * @param func func
   * @param <TResult> 结果
   * @return TResult
   */
  <TResult> TResult call(String sql, Function<CallableStatement, TResult> func);

  <TResult> TResult call(
          String sql, Function<CallableStatement, TResult> func, int queryTimeout);

  /**
   * 执行SQL，返回多行记录
   *
   * @param viewClass 结果集类型
   * @param sql SQL语句
   * @param params 参数
   * @param <TView> 结果集类型泛型
   * @return 结果集
   */
  <TView> List<TView> find(Class<TView> viewClass, String sql, Collection params);

  /**
   * 执行一个SQL语句
   *
   * @param sql SQL语句
   * @param params 参数
   * @param queryTimeOut 超时时间
   * @return 影响行数
   */
  int execute(String sql, Collection params, int queryTimeOut);

  int create(
      String sql, Collection params, boolean autoGeneratedPK, Consumer<ResultSet> pkConsumer);

  int createBatch(
          String sql,
          Collection<Collection> paramsList,
          boolean autoGeneratedPK,
          Consumer<ResultSet> consumer);

  int updateBatch(String sql, Collection<Collection> paramsList);
}
