package work.myfavs.framework.orm.orm.component;

import com.alibaba.druid.sql.ast.SQLExpr;
import com.alibaba.druid.sql.ast.expr.SQLIntegerExpr;
import com.alibaba.druid.sql.ast.statement.SQLInsertStatement;
import work.myfavs.framework.orm.*;
import work.myfavs.framework.orm.meta.Record;
import work.myfavs.framework.orm.meta.clause.Sql;
import work.myfavs.framework.orm.meta.enumeration.GenerationType;
import work.myfavs.framework.orm.meta.schema.Attribute;
import work.myfavs.framework.orm.meta.schema.ClassMeta;
import work.myfavs.framework.orm.meta.schema.Metadata;
import work.myfavs.framework.orm.util.common.CollectionUtil;
import work.myfavs.framework.orm.util.common.DruidUtil;
import work.myfavs.framework.orm.util.exception.InvalidDataAccessException;
import work.myfavs.framework.orm.util.id.PKGenerator;

import java.util.*;

/**
 * 实体插入器，处理实体创建和批量创建逻辑。
 * <p>根据主键策略和数据库类型自动选择最佳批量插入策略：</p>
 * <ul>
 *   <li>{@link GenerationType#IDENTITY} + SQL Server → {@code OUTPUT INSERTED} 多行 INSERT</li>
 *   <li>{@link GenerationType#IDENTITY} + 其他 → JDBC {@code executeBatch()} + {@code getGeneratedKeys()}</li>
 *   <li>非自增主键 → 多行 VALUES 批量 INSERT</li>
 * </ul>
 */
public class OrmInserter {

  private final Database database;
  private final DBTemplate dbTemplate;
  private final OrmSqlBuilder sqlBuilder;
  private final OrmExecutor executor;

  /**
   * 构造 OrmInserter 实例.
   *
   * @param database   {@link Database} 实例
   * @param dbTemplate {@link DBTemplate} 实例，用于获取主键生成器
   * @param sqlBuilder {@link OrmSqlBuilder} 实例
   * @param executor   {@link OrmExecutor} 实例
   */
  public OrmInserter(Database database, DBTemplate dbTemplate, OrmSqlBuilder sqlBuilder, OrmExecutor executor) {
    this.database = database;
    this.dbTemplate = dbTemplate;
    this.sqlBuilder = sqlBuilder;
    this.executor = executor;
  }

  /**
   * 创建单条实体记录。
   * <p>非自增主键由 {@link GenerationType} 策略自动生成；自增主键通过 JDBC {@code RETURN_GENERATED_KEYS} 回读。</p>
   *
   * @param modelClass 实体类型
   * @param entity     实体实例
   * @param <TModel>   实体类型泛型
   * @return 影响行数
   */
  public <TModel> int create(Class<TModel> modelClass, TModel entity) {

    if (null == entity) return 0;

    final ClassMeta classMeta = Metadata.entityMeta(modelClass);
    final Attribute primaryKey = classMeta.checkPrimaryKey();
    final Attribute logicDelete = classMeta.getLogicDelete();
    final GenerationType strategy = classMeta.getStrategy();
    final String tableName = OrmSqlBuilder.getTableName(classMeta);

    final Map<String, Attribute> updateAttributes = classMeta.getUpdateAttributes();

    boolean autoGeneratedPK = false;

    final Sql sql = new Sql();

    final SQLInsertStatement insertStatement = DruidUtil.createSQLInsertStatement(tableName);
    final List<SQLExpr> columns = new ArrayList<>();
    final List<SQLExpr> values = new ArrayList<>();

    if (strategy == GenerationType.IDENTITY) {
      autoGeneratedPK = true;
    } else {
      columns.add(DruidUtil.createColumn(primaryKey.getColumnName()));
      values.add(DruidUtil.createParam());

      Object pkVal = generatePrimaryKey(strategy, primaryKey, entity);
      sql.getParams().add(pkVal);
    }

    for (Attribute attr : updateAttributes.values()) {
      columns.add(DruidUtil.createColumn(attr.getColumnName()));
      values.add(DruidUtil.createParam());

      sql.getParams().add(attr.getValue(entity));
    }

    if (null != logicDelete) {
      columns.add(DruidUtil.createColumn(logicDelete.getColumnName()));
      values.add(new SQLIntegerExpr(0));
    }

    insertStatement.getColumns().addAll(columns);
    insertStatement.setValues(new SQLInsertStatement.ValuesClause(values));

    sql.append(insertStatement.toUnformattedString());

    try (Query query = this.database.createQuery(sql.toString(), autoGeneratedPK)) {
      return query.addParameters(sql.getParams())
          .execute(null,
              rs -> primaryKey.setPrimaryKey(entity, rs));
    }
  }

  /**
   * 批量创建实体记录。
   * <p>根据主键策略和数据库类型自动选择最佳批量插入策略:
   * 非自增主键走多行 VALUES；IDENTITY + SQL Server 走 OUTPUT INSERTED；
   * IDENTITY + 其他走 JDBC Batch。</p>
   *
   * @param modelClass 实体类型
   * @param entities   实体集合
   * @param <TModel>   实体类型泛型
   * @return 影响行数
   */
  public <TModel> int create(Class<TModel> modelClass, Collection<TModel> entities) {
    if (CollectionUtil.isEmpty(entities)) return 0;

    final ClassMeta classMeta = Metadata.entityMeta(modelClass);
    final boolean isIdentity = classMeta.getStrategy() == GenerationType.IDENTITY;

    if (isIdentity) {
      if (this.database.isSqlServer()) {
        return createInOutputBatch(modelClass, entities);
      }
      return createInJdbcBatch(classMeta, entities);
    }

    return createInSqlBatch(classMeta, entities);
  }

  private <TModel> int createInOutputBatch(Class<TModel> modelClass, Collection<TModel> entities) {
    final ClassMeta entityMeta = Metadata.entityMeta(modelClass);
    final Attribute primaryKey = entityMeta.checkPrimaryKey();
    final Map<String, Attribute> updateAttributes = entityMeta.getUpdateAttributes();
    final Attribute logicDelete = entityMeta.getLogicDelete();
    final String tableName = OrmSqlBuilder.getTableName(entityMeta);

    final int batchSize = this.database.getDbConfig().getBatchSize();
    final List<List<TModel>> batchList = CollectionUtil.split(entities, batchSize);

    int result = 0;

    for (List<TModel> entityList : batchList) {
      StringBuilder sqlBuilder = new StringBuilder();
      sqlBuilder.append("INSERT INTO ").append(tableName).append(" (");

      boolean firstCol = true;
      for (Attribute attr : updateAttributes.values()) {
        if (!firstCol) sqlBuilder.append(", ");
        sqlBuilder.append(attr.getColumnName());
        firstCol = false;
      }
      if (null != logicDelete) {
        if (!firstCol) sqlBuilder.append(", ");
        sqlBuilder.append(logicDelete.getColumnName());
      }

      sqlBuilder.append(") OUTPUT INSERTED.").append(primaryKey.getColumnName()).append(" VALUES ");

      Sql sql = new Sql();
      for (int i = 0; i < entityList.size(); i++) {
        TModel entity = entityList.get(i);
        if (i > 0) sqlBuilder.append(", ");
        sqlBuilder.append("(");
        boolean firstVal = true;
        for (Attribute attr : updateAttributes.values()) {
          if (!firstVal) sqlBuilder.append(", ");
          sqlBuilder.append("?");
          sql.getParams().add(attr.getValue(entity));
          firstVal = false;
        }
        if (null != logicDelete) {
          if (!firstVal) sqlBuilder.append(", ");
          sqlBuilder.append("?");
          sql.getParams().add(0);
        }
        sqlBuilder.append(")");
      }

      sql.append(sqlBuilder.toString());

      try (Query query = this.database.createQuery(sql.toString())) {
        query.addParameters(sql.getParams());
        List<Record> records = query.find(Record.class);
        for (int i = 0; i < entityList.size(); i++) {
          Object id = records.get(i).get(primaryKey.getColumnName());
          primaryKey.setValue(entityList.get(i), id);
        }
        result += entityList.size();
      }
    }

    return result;
  }

  private <TModel> int createInSqlBatch(ClassMeta entityMeta, Collection<TModel> entities) {

    int result = 0;

    final Map<String, Attribute> updateAttributes = entityMeta.getUpdateAttributes();
    final String tableName = OrmSqlBuilder.getTableName(entityMeta);
    final GenerationType strategy = entityMeta.getStrategy();
    final Attribute primaryKey = entityMeta.checkPrimaryKey();

    final List<Sql> sqlList = new ArrayList<>();

    final int batchSize = this.database.getDbConfig().getBatchSize();
    final List<List<TModel>> batchList = CollectionUtil.split(entities, batchSize);

    for (List<TModel> entityList : batchList) {
      boolean insertClauseCompleted = false;
      Sql insertClause = Sql.create(String.format("INSERT INTO %s (", tableName));
      Sql valuesClause = Sql.create(") VALUES ");

      for (TModel entity : entityList) {
        Object pkVal = generatePrimaryKey(strategy, primaryKey, entity);

        if (!insertClauseCompleted) {
          insertClause.append(primaryKey.getColumnName() + ",");
        }
        valuesClause.append("(?,", pkVal);

        for (Attribute attr : updateAttributes.values()) {
          if (!insertClauseCompleted) {
            insertClause.append(attr.getColumnName() + ",");
          }
          valuesClause.append("?,", attr.getFieldVisitor().getValue(entity));
        }

        if (null != entityMeta.getLogicDelete()) {
          if (!insertClauseCompleted) {
            insertClause.append(entityMeta.getLogicDelete().getColumnName() + ",");
          }

          valuesClause.append("?,", 0);
        }

        if (!insertClauseCompleted) {
          insertClause.deleteLast(",");
          insertClauseCompleted = true;
        }
        valuesClause.deleteLast(",");
        valuesClause.append("),");
      }

      valuesClause.deleteLast(",");
      sqlList.add(insertClause.append(valuesClause));
    }

    for (Sql batchSql : sqlList) {
      result += this.executor.execute(batchSql);
    }
    return result;
  }

  private <TModel> int createInJdbcBatch(ClassMeta classMeta, Collection<TModel> entities) {

    final Attribute primaryKey = classMeta.checkPrimaryKey();
    final GenerationType strategy = classMeta.getStrategy();
    final Map<String, Attribute> updateAttributes = classMeta.getUpdateAttributes();

    final Sql sql = new Sql(this.sqlBuilder.insert(classMeta));
    final Collection<Collection<?>> paramsList = new ArrayList<>();

    boolean autoGeneratedPK = strategy == GenerationType.IDENTITY;

    for (TModel entity : entities) {
      final Collection<Object> params = new ArrayList<>();

      if (!autoGeneratedPK) {
        params.add(generatePrimaryKey(strategy, primaryKey, entity));
      }

      for (Attribute attr : updateAttributes.values()) {
        params.add(attr.getFieldVisitor().getValue(entity));
      }

      paramsList.add(params);
    }

    try (Query query = this.database.createQuery(sql.toString(), autoGeneratedPK)) {
      for (Collection<?> batchParams : paramsList) {
        query.addParameters(batchParams).addBatch();
      }
      return query.executeBatch(rs -> primaryKey.setPrimaryKeys(entities, rs)).length;
    }
  }

  private <TModel> Object generatePrimaryKey(GenerationType strategy, Attribute primaryKey, TModel entity) {
    Object pkVal = primaryKey.getValue(entity);

    if (null == pkVal) {
      PKGenerator pkGenerator = this.dbTemplate.getPkGenerator();
      switch (strategy) {
        case SNOW_FLAKE:
          pkVal = pkGenerator.nextSnowFakeId();
          break;
        case UUID:
          pkVal = pkGenerator.nextUUID();
          break;
        case ASSIGNED:
          throw new InvalidDataAccessException("使用 ASSIGNED 主键策略时，必须要为主键赋值.");
        default:
          throw new InvalidDataAccessException("自动生成主键失败.");
      }

      primaryKey.setValue(entity, pkVal);
    }
    return pkVal;
  }
}
