<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <artifactId>orm-spring-starter</artifactId>
  <packaging>jar</packaging>
  <modelVersion>4.0.0</modelVersion>

  <name>${project.groupId}.${project.artifactId}</name>
  <description>Spring 2.x starter for the myfavs database orm framework</description>
  <url>https://github.com/tanqimin/MyFavsORM</url>

  <parent>
    <groupId>work.myfavs.framework</groupId>
    <artifactId>pom</artifactId>
    <version>1.0.0-260115-1-SNAPSHOT</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>work.myfavs.framework</groupId>
      <artifactId>orm</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.springframework/spring-jdbc -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-jdbc</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- https://mvnrepository.com/artifact/junit/junit -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.mockito/mockito-core -->
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
    </dependency>
  </dependencies>
</project>