package work.myfavs.framework.orm;

import work.myfavs.framework.orm.meta.DbType;
import work.myfavs.framework.orm.orm.Orm;
import work.myfavs.framework.orm.orm.OrmFactory;
import work.myfavs.framework.orm.util.common.StringUtil;
import work.myfavs.framework.orm.util.exception.ConnectionException;
import work.myfavs.framework.orm.util.func.ThrowingConsumer;
import work.myfavs.framework.orm.util.func.ThrowingFunction;

import java.io.Closeable;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Savepoint;

/**
 * 数据库
 */
public class Database implements Closeable {

  protected final DBTemplate  dbTemplate;
  protected final ConnFactory connFactory;

  private Query query;

  /**
   * 获取 {@link DBTemplate}
   *
   * @return {@link DBTemplate}
   */
  public DBTemplate getDbTemplate() {
    return dbTemplate;
  }

  /**
   * 构造方法，建议通过 {@link DBTemplate#createDatabase()} 创建
   *
   * @param dbTemplate {@link DBTemplate}
   */
  public Database(DBTemplate dbTemplate) {
    this.dbTemplate  = dbTemplate;
    this.connFactory = dbTemplate.getConnectionFactory();
    this.open();
  }

  /**
   * 判断当前是否使用 SQL Server 数据库
   * <p>每次调用都会从配置中读取数据库类型进行判断，结果不缓存</p>
   *
   * @return 如果是返回 {@code true}，否则返回 {@code false}
   */
  public boolean isSqlServer() {
    final String dbType = getDbConfig().getDbType();
    return StringUtil.equals(dbType, DbType.SQL_SERVER)
        || StringUtil.equals(dbType, DbType.SQL_SERVER_2012);
  }

  /**
   * 判断当前是否使用 MySql 数据库
   *
   * @return 如果是返回 {@code true}，否则返回 {@code false}
   */
  public boolean isMySql() {
    return StringUtil.equals(getDbConfig().getDbType(), DbType.MYSQL);
  }

  /**
   * 获取ORM数据库配置
   *
   * @return {@link DBTemplate#getDbConfig()}
   */
  public DBConfig getDbConfig() {
    return this.dbTemplate.getDbConfig();
  }

  /**
   * 获取当前数据库连接
   *
   * @return 数据库连接
   */
  public Connection getConnection() {
    return this.connFactory.getCurrentConnection();
  }

  /**
   * 打开数据库连接，需要与 {@link #close()} 配对使用
   *
   * @return 如果连接不存在，则创建，否则记录数据库连接打开次数 {@code +1}，并返回 {@link ConnFactory#openConnection()}
   */
  @SuppressWarnings("resource")
  public Database open() {
    this.connFactory.openConnection();
    return this;
  }

  /**
   * 释放数据库资源，与 {@link #open()} 配对使用 <br/>
   * 如果数据库连接打开次数 {@code > 1} ，则记录数据库连接次数 {@code -1} <br/>
   * 如果数据库连接打开次数 {@code = 1} ，则关闭数据库连接 <br/>
   * 即使关闭 Query 时发生异常，也会通过 try-finally 确保释放数据库连接
   */
  @Override
  public void close() {
    try {
      if (null != this.query) {
        this.query.close();
      }
    } finally {
      this.connFactory.closeConnection(getConnection());
      this.query = null;
    }
  }

  /**
   * 查询，设置 SQL 语句，并创建数据库 PrepareStatement 对象 <br>
   *
   * @param sql SQL 语句
   * @return {@link Database}
   */
  public Query createQuery(String sql) {
    return createQuery(sql, false);
  }

  /**
   * 查询，设置 SQL 语句，并创建数据库 PrepareStatement 对象 <br>
   *
   * @param sql             SQL 语句
   * @param autoGeneratedPK 是否生成主键
   * @return {@link Database}
   */
  public Query createQuery(String sql, boolean autoGeneratedPK) {
    if (null == this.query) {
      return this.query = new Query(this, sql, autoGeneratedPK);
    }
    return this.query.createQuery(sql, autoGeneratedPK);
  }

  /**
   * 创建 ORM 实例
   *
   * @return {@link Orm}
   */
  public Orm createOrm() {
    return OrmFactory.createOrm(this);
  }


  /**
   * 设置保存点（无名称）
   *
   * @return {@link Savepoint}
   * @throws ConnectionException 当前未获取到数据库连接或设置保存点时发生异常
   */
  public Savepoint setSavepoint() {
    try {
      final Connection connection = getConnection();
      if (null == connection) {
        throw new ConnectionException("当前未获取到数据库连接，无法设置 Savepoint");
      }
      return connection.setSavepoint();
    } catch (SQLException e) {
      throw new ConnectionException(e, "设置 Savepoint 时发生异常: %s", e.getMessage());
    }
  }

  /**
   * 设置指定名称的保存点
   *
   * @param name 保存点名称
   * @return {@link Savepoint}
   * @throws ConnectionException 当前未获取到数据库连接或设置保存点时发生异常
   */
  public Savepoint setSavepoint(String name) {
    try {
      final Connection connection = getConnection();
      if (null == connection) {
        throw new ConnectionException("当前未获取到数据库连接，无法设置 Savepoint");
      }
      return connection.setSavepoint(name);
    } catch (SQLException e) {
      throw new ConnectionException(e, "设置 Savepoint 时发生异常: %s", e.getMessage());
    }
  }

  /**
   * 回滚事务
   *
   * @throws ConnectionException 回滚事务时发生异常
   */
  public void rollback() {
    rollback(null);
  }

  /**
   * 回滚事务到指定保存点
   *
   * @param savepoint {@link Savepoint}，为 {@code null} 时回滚整个事务
   * @throws ConnectionException 回滚事务时发生异常
   */
  public void rollback(Savepoint savepoint) {
    Connection connection = getConnection();
    if (null == connection) {
      return;
    }

    try {
      if (null == savepoint) {
        connection.rollback();
        return;
      }
      connection.rollback(savepoint);

    } catch (SQLException e) {
      throw new ConnectionException(e, "回滚事务时发生异常: %s", e.getMessage());
    }
  }

  /**
   * 提交事务
   *
   * @throws ConnectionException 提交事务时发生异常
   */
  public void commit() {

    Connection connection = getConnection();
    if (null == connection) {
      return;
    }

    try {
      if (connection.getAutoCommit()) {
        return;
      }
      if (connection.isClosed()) {
        return;
      }

      connection.commit();
    } catch (SQLException e) {
      throw new ConnectionException(e, "提交事务时发生异常: %s", e.getMessage());
    }
  }

  /**
   * 在事务中执行 {@link ThrowingFunction#apply(Object)}
   *
   * @param func      {@link ThrowingFunction} function
   * @param <TResult> function 返回结果类型
   * @return {@link ThrowingFunction#apply(Object) func.apply(Object)}
   */
  public <TResult> TResult tx(ThrowingFunction<Orm, TResult, SQLException> func) {

    return tx(func, () -> {});
  }

  /**
   * 在事务中执行 {@link ThrowingFunction#apply(Object)}，并在事务完成后执行 {@link Runnable#run()}
   *
   * @param func      {@link ThrowingFunction} function
   * @param callback  {@link Runnable} callback
   * @param <TResult> function 返回结果类型
   * @return {@link ThrowingFunction#apply(Object) func.apply(Object)}
   */
  public <TResult> TResult tx(ThrowingFunction<Orm, TResult, SQLException> func, Runnable callback) {

    this.open();
    try {
      Orm     orm    = this.createOrm();
      TResult result = func.apply(orm);
      this.commit();
      callback.run();
      return result;
    } catch (SQLException e) {
      try {
        this.rollback();
      } catch (Exception rollbackEx) {
        e.addSuppressed(rollbackEx);
      }
      throw new ConnectionException(e, "执行事务过程中发生异常: %s", e.getMessage());
    } finally {
      this.close();
    }
  }

  /**
   * 在事务中执行 {@link ThrowingConsumer#accept(Object)}
   *
   * @param consumer {@link ThrowingConsumer} consumer
   */
  public void tx(ThrowingConsumer<Orm, SQLException> consumer) {

    tx(consumer, () -> {});
  }

  /**
   * 在事务中执行 {@link ThrowingConsumer#accept(Object)}，并在事务完成后执行 {@link Runnable#run()}
   *
   * @param consumer {@link ThrowingConsumer} consumer
   * @param callback {@link Runnable} callback
   */
  public void tx(ThrowingConsumer<Orm, SQLException> consumer, Runnable callback) {

    this.open();
    try {
      Orm orm = this.createOrm();
      consumer.accept(orm);
      this.commit();
      callback.run();
    } catch (SQLException e) {
      try {
        this.rollback();
      } catch (Exception rollbackEx) {
        e.addSuppressed(rollbackEx);
      }
      throw new ConnectionException(e, "执行事务过程中发生异常: %s", e.getMessage());
    } finally {
      this.close();
    }
  }
}
