debug: false
logging:
  level:
    ROOT: debug
spring:
  banner:
    charset: utf-8
  datasource:
    primary:
      db-type: sqlserver2012
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.8.246:1433;DatabaseName=myfavs_master;sendStringParametersAsUnicode=false;encrypt=false
      username: sa
      password: sa
    druid:
      default-auto-commit: false
#      url: jdbc:mysql://192.168.8.34:13307/sstest?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&useLocalSessionState=true&rewriteBatchedStatements=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&elideSetAutoCommits=true&maintainTimeStats=false
#      username: root
#      password: 9527