POST http://127.0.0.1:9527/user/save
Content-Type: application/json
Cache-control: no-cache
tenant-name: master

{
  "username": "tanqimin",
  "email": "karl_tan@126.com",
  "password": "123456",
  "userType": "ADMIN",
  "created": "2022-02-11 12:00:00",
  "modified": "2022-02-11 12:00:01"
}

#################
GET http://127.0.0.1:9527/user/find-by-page
tenant-name: master

#################
POST http://127.0.0.1:9527/user/save
Content-Type: application/json
Cache-control: no-cache
tenant-name: tenant1

{
  "username": "tanqimin",
  "email": "karl_tan@tenant1.com",
  "password": "123456",
  "userType": "ADMIN",
  "created": "2022-02-11 12:00:00",
  "modified": "2022-02-11 12:00:01"
}

#################
GET http://127.0.0.1:9527/user/find-by-page
tenant-name: tenant1

#################
POST http://127.0.0.1:9527/user/save
Content-Type: application/json
Cache-control: no-cache
tenant-name: tenant2

{
  "username": "tanqimin",
  "email": "karl_tan@tenant2.com",
  "password": "123456",
  "userType": "ADMIN",
  "created": "2022-02-11 12:00:00",
  "modified": "2022-02-11 12:00:01"
}

#################
GET http://127.0.0.1:9527/user/find-by-page
tenant-name: tenant2

#################
POST http://127.0.0.1:9527/user/save
Content-Type: application/json
Cache-control: no-cache
tenant-name: tenant3

{
  "username": "tanqimin",
  "email": "karl_tan@tenant3.com",
  "password": "123456",
  "userType": "ADMIN",
  "created": "2022-02-11 12:00:00",
  "modified": "2022-02-11 12:00:01"
}

#################
GET http://127.0.0.1:9527/user/find-by-page
tenant-name: tenant3